[build]
  command = "echo \"Hello world!\""

[[plugins]]
  package = "./_plugins/netlify-plugin-redirects"
  [plugins.inputs]
    source = "./redirects.csv"
    destination = "./_redirects"
    defaultBranch = "master"
